"""Phase 8 Candidate: X-STRASSEN-ANGULAR
Description: Angular moment propagation combined with 1-level Strassen kernel (>=512)
Autogenerated standalone estimator for Phase 8.
Pure flopscope.numpy and native flopscope operations only.
"""

from __future__ import annotations

import flopscope as flops
import flopscope.numpy as fnp
from whestbench import BaseEstimator, SetupContext
from whestbench.domain import MLP

try:
    flops.configure(symmetry_warnings=False)
except Exception:
    pass

A1_CONST = 0.9997558892211914


def _wick_base(mean, var):
    sigma = fnp.sqrt(fnp.maximum(var, fnp.asarray(1e-12, dtype=fnp.float32)))
    alpha = mean / sigma
    return sigma, alpha, flops.stats.norm.pdf(alpha).astype(fnp.float32), flops.stats.norm.cdf(alpha).astype(fnp.float32)


def _relu_wick(mean: fnp.ndarray, var: fnp.ndarray, k: int, p: int, base=None) -> fnp.ndarray:
    sigma, alpha, phi, cdf = _wick_base(mean, var) if base is None else base
    if p == 1:
        if k == 0: return sigma * phi + mean * cdf
        if k == 1: return cdf
        if k == 2: return phi / sigma
        if k == 3: return -alpha * phi / (sigma**2)
        if k == 4: return (alpha**2 - 1.0) * phi / (sigma**3)
    elif p == 2:
        if k == 0: return (mean**2 + var) * cdf + mean * sigma * phi
        if k == 1: return 2.0 * (sigma * phi + mean * cdf)
        if k == 2: return 2.0 * cdf
        if k == 3: return 2.0 * phi / sigma
        if k == 4: return -2.0 * alpha * phi / (sigma**2)
    elif p == 3:
        if k == 0: return (sigma**3) * ((2.0 + alpha**2) * phi + (3.0 * alpha + alpha**3) * cdf)
        if k == 1: return 3.0 * (sigma**2) * (alpha * phi + (1.0 + alpha**2) * cdf)
        if k == 2: return 6.0 * (sigma * phi + mean * cdf)
        if k == 3: return 6.0 * cdf
        if k == 4: return 6.0 * phi / sigma
    elif p == 4:
        if k == 0: return (sigma**4) * ((5.0 * alpha + alpha**3) * phi + (3.0 + 6.0 * alpha**2 + alpha**4) * cdf)
        if k == 1: return 4.0 * (sigma**3) * ((2.0 + alpha**2) * phi + (3.0 * alpha + alpha**3) * cdf)
        if k == 2: return 12.0 * (sigma**2) * (alpha * phi + (1.0 + alpha**2) * cdf)
        if k == 3: return 24.0 * (sigma * phi + mean * cdf)
        if k == 4: return 24.0 * cdf
    raise ValueError(f"Unsupported Wick pair ({k}, {p})")


def _zero_diag(mat: fnp.ndarray) -> fnp.ndarray:
    res = mat.copy()
    fnp.fill_diagonal(res, 0.0)
    return res


def _sym(mat: fnp.ndarray) -> fnp.ndarray:
    return 0.5 * (mat + mat.T)


def _matmul_strassen(A: fnp.ndarray, B: fnp.ndarray) -> fnp.ndarray:
    if A.ndim < 2 or B.ndim < 2:
        return A @ B
    m, k = A.shape
    k2, p = B.shape
    if min(m, k, p) < 512:
        return A @ B
    m_pad = m + (m % 2)
    k_pad = k + (k % 2)
    p_pad = p + (p % 2)
    A_p = fnp.pad(A, ((0, m % 2), (0, k % 2))) if (m % 2 != 0 or k % 2 != 0) else A
    B_p = fnp.pad(B, ((0, k % 2), (0, p % 2))) if (k % 2 != 0 or p % 2 != 0) else B

    m2, k2_h, p2 = m_pad // 2, k_pad // 2, p_pad // 2
    A11, A12 = A_p[:m2, :k2_h], A_p[:m2, k2_h:]
    A21, A22 = A_p[m2:, :k2_h], A_p[m2:, k2_h:]
    B11, B12 = B_p[:k2_h, :p2], B_p[:k2_h, p2:]
    B21, B22 = B_p[k2_h:, :p2], B_p[k2_h:, p2:]

    M1 = (A11 + A22) @ (B11 + B22)
    M2 = (A21 + A22) @ B11
    M3 = A11 @ (B12 - B22)
    M4 = A22 @ (B21 - B11)
    M5 = (A11 + A12) @ B22
    M6 = (A21 - A11) @ (B11 + B12)
    M7 = (A12 - A22) @ (B21 + B22)

    C11 = M1 + M4 - M5 + M7
    C12 = M3 + M5
    C21 = M2 + M4
    C22 = M1 - M2 + M3 + M6

    top = fnp.concatenate([C11, C12], axis=1)
    bot = fnp.concatenate([C21, C22], axis=1)
    C_full = fnp.concatenate([top, bot], axis=0)
    return C_full[:m, :p]


def _mm(A: fnp.ndarray, B: fnp.ndarray) -> fnp.ndarray:
    return _matmul_strassen(A, B)


class Estimator(BaseEstimator):
    def setup(self, ctx: SetupContext) -> None:
        pass

    def predict(self, mlp: MLP, budget: int) -> fnp.ndarray:
        _ = budget
        depth = mlp.depth
        n = mlp.width
        eye_n = fnp.eye(n, dtype=fnp.float32)

        is_angular = True
        use_k4 = True
        k3_mode = "c65"

        # Initial state setup
        if is_angular:
            mu = fnp.zeros(n, dtype=fnp.float32)
            cov = fnp.eye(n, dtype=fnp.float32)
            c4 = float(-6.0 / (n + 2.0)) if use_k4 else 0.0
        else:
            mu = fnp.zeros(n, dtype=fnp.float32)
            cov = fnp.eye(n, dtype=fnp.float32)
            c4 = 0.0

        U = fnp.zeros((n, 0), dtype=fnp.float32)
        V = fnp.zeros((n, 0), dtype=fnp.float32)
        col_birth_layers: list[int] = []
        comp_layers = {6, 10, 13}
        per_layer_ret = {6: 0.8, 10: 0.9, 13: 0.8}
        has_penult = False
        penult_A2 = None
        penult_h = None
        penult_A_ds = None

        # Pilot storage for direct contraction mode
        pilot_data = [] if k3_mode == "direct_term" else None

        preds = []

        for l in range(depth):
            W_ref = fnp.asarray(mlp.weights[l], dtype=fnp.float32).T
            terminal = (l == depth - 1)

            # --- Terminal layer handling ---
            if terminal:
                mu_pre = W_ref @ mu
                var_pre = fnp.sum((W_ref @ cov) * W_ref, axis=1)
                d_M = fnp.sum(W_ref * W_ref, axis=1)

                if k3_mode == "c65":
                    if has_penult:
                        d_terminal_old = fnp.sum(_mm(W_ref, U)**2 * _mm(W_ref, V), axis=1) if U.shape[1] else fnp.zeros(n, dtype=fnp.float32)
                        d_terminal_path = 3.0 * fnp.sum(_mm(W_ref, penult_A2)**2 * W_ref * penult_h[None, :], axis=1)
                        d_terminal_slice = fnp.sum((W_ref**2) * _mm(W_ref, penult_A_ds), axis=1)
                        s3 = d_terminal_old + d_terminal_path + d_terminal_slice
                    else:
                        if U.shape[1]:
                            U_pre = _mm(W_ref, U)
                            V_pre = _mm(W_ref, V)
                            s3 = fnp.sum(U_pre * U_pre * V_pre, axis=1)
                        else:
                            s3 = fnp.zeros(n, dtype=fnp.float32)
                elif k3_mode == "direct_term":
                    # Backward suffix contraction of frozen pilot sources into d_15
                    d_target = fnp.zeros(n, dtype=fnp.float32)
                    Q_curr = W_ref.copy()
                    for j in range(depth - 2, -1, -1):
                        p_j = pilot_data[j]
                        U_j = p_j["U_birth"]
                        V_j = p_j["V_birth"]
                        u_p = Q_curr @ U_j
                        v_p = Q_curr @ V_j
                        d_target = d_target + fnp.sum((u_p * u_p) * v_p, axis=1)
                        if j > 0:
                            g_j = p_j["g"]
                            W_j_T = fnp.asarray(mlp.weights[j], dtype=fnp.float32).T
                            Q_curr = (Q_curr * g_j[None, :]) @ W_j_T
                    s3 = d_target
                else:
                    s3 = fnp.zeros(n, dtype=fnp.float32)

                s4 = c4 * (d_M**2) if use_k4 else fnp.zeros(n, dtype=fnp.float32)
                base = _wick_base(mu_pre, var_pre)
                mu = (_relu_wick(mu_pre, var_pre, 0, 1, base)
                      + _relu_wick(mu_pre, var_pre, 3, 1, base) * s3 / 6.0
                      + _relu_wick(mu_pre, var_pre, 4, 1, base) * s4 / 24.0)

                # Final representation conversion
                if is_angular:
                    mu_out = mu * A1_CONST
                else:
                    mu_out = mu

                preds.append(mu_out)
                break

            # --- Internal layer linear step ---
            if l == 0:
                M = W_ref @ W_ref.T
                cov_pre = _sym(M)
                mu_pre = fnp.zeros(n, dtype=fnp.float32)
                d_M = fnp.diag(M)
                s3 = fnp.zeros(n, dtype=fnp.float32)
                s21 = fnp.zeros((n, n), dtype=fnp.float32)
                sum_pre = fnp.zeros((n, n), dtype=fnp.float32)
                U_pre = fnp.zeros((n, 0), dtype=fnp.float32)
                V_pre = fnp.zeros((n, 0), dtype=fnp.float32)
            else:
                mu_pre = W_ref @ mu
                W_cov = W_ref @ cov
                cov_pre = _sym(W_cov @ W_ref.T)
                M = W_ref @ W_ref.T
                d_M = fnp.sum(W_ref * W_ref, axis=1)

                if k3_mode == "c65" and U.shape[1] > 0:
                    U_pre = _mm(W_ref, U)
                    V_pre = _mm(W_ref, V)
                    s3 = fnp.sum(U_pre * U_pre * V_pre, axis=1)
                    sum_pre = 2.0 * _mm(U_pre * V_pre, U_pre.T) + _mm(U_pre * U_pre, V_pre.T)
                    s21 = (1.0 / 3.0) * _zero_diag(sum_pre)
                else:
                    s3 = fnp.zeros(n, dtype=fnp.float32)
                    s21 = fnp.zeros((n, n), dtype=fnp.float32)
                    sum_pre = fnp.zeros((n, n), dtype=fnp.float32)
                    U_pre = fnp.zeros((n, 0), dtype=fnp.float32)
                    V_pre = fnp.zeros((n, 0), dtype=fnp.float32)

            if use_k4:
                s4 = c4 * (d_M**2)
                s22 = (1.0 / 3.0) * c4 * _zero_diag(d_M[:, None] * d_M[None, :] + 2.0 * (M**2))
            else:
                s4 = fnp.zeros(n, dtype=fnp.float32)
                s22 = fnp.zeros((n, n), dtype=fnp.float32)

            # --- Nonlinear step ---
            var_pre = fnp.diag(cov_pre)
            base = _wick_base(mu_pre, var_pre)
            wick_cache = {}

            def w(k, p):
                key = (k, p)
                if key not in wick_cache:
                    wick_cache[key] = _relu_wick(mu_pre, var_pre, k, p, base)
                return wick_cache[key]

            cov11 = _zero_diag(cov_pre)

            pk = {}
            for p in (1, 2, 3, 4):
                pk[(p,)] = w(0, p) + (1.0 / 6.0) * w(3, p) * s3 + (1.0 / 24.0) * w(4, p) * s4

            pk[(1, 1)] = _sym(
                cov11 * (w(1, 1)[:, None] * w(1, 1)[None, :])
                + s21.T * (w(1, 1)[:, None] * w(2, 1)[None, :])
                + 0.5 * (cov11**2) * (w(2, 1)[:, None] * w(2, 1)[None, :])
                + 0.25 * s22 * (w(2, 1)[:, None] * w(2, 1)[None, :])
            )

            pk[(2, 1)] = (
                cov11 * (w(1, 2)[:, None] * w(1, 1)[None, :])
                + 0.5 * s21.T * (w(1, 2)[:, None] * w(2, 1)[None, :])
                + 0.5 * s21 * (w(2, 2)[:, None] * w(1, 1)[None, :])
                + 0.5 * (cov11**2) * (w(2, 2)[:, None] * w(2, 1)[None, :])
                + 0.25 * s22 * (w(2, 2)[:, None] * w(2, 1)[None, :])
            )

            pk1, pk2, pk3, pk4 = pk[(1,)], pk[(2,)], pk[(3,)], pk[(4,)]
            pk11, pk21 = pk[(1, 1)], pk[(2, 1)]

            k1 = pk1
            k2 = pk2 - pk1**2
            k3 = pk3 - 3.0 * pk1 * pk2 + 2.0 * (pk1**3)
            k4 = pk4 - 4.0 * pk1 * pk3 - 3.0 * (pk2**2) + 12.0 * (pk1**2) * pk2 - 6.0 * (pk1**4)
            k11 = pk11
            k21 = _zero_diag(pk21 - 2.0 * (pk1[:, None] * pk11))

            w11 = w(1, 1)
            w21 = w(2, 1)

            # Sources for K3
            s3_pk = s3 * (w11**3)
            A2 = w11[:, None] * cov11
            C2 = (w21[:, None] * w11[None, :] * cov11).T
            s21_pk = (1.0 / 3.0) * _zero_diag(
                sum_pre * (w11[:, None]**2) * (w11[None, :]) + 3.0 * (A2 * C2)
            )

            k3_ds = k3 - s3_pk
            k21_ds = k21 - s21_pk
            A_ds = fnp.diag(k3_ds) + 3.0 * k21_ds.T

            if k3_mode == "direct_term":
                # Save frozen source descriptors for pilot
                sigma_p = fnp.sqrt(fnp.maximum(var_pre, fnp.asarray(1e-12, dtype=fnp.float32)))
                g_l = flops.stats.norm.cdf(mu_pre / sigma_p).astype(fnp.float32)
                U_birth = fnp.concatenate([A2, eye_n], axis=1)
                V_birth = fnp.concatenate([3.0 * eye_n * w21[None, :], A_ds], axis=1)
                pilot_data.append({"g": g_l, "U_birth": U_birth, "V_birth": V_birth})

            elif k3_mode == "c65":
                if l == depth - 2:
                    has_penult = True
                    penult_A2 = A2
                    penult_h = w21
                    penult_A_ds = A_ds
                    if U_pre.shape[1] > 0:
                        U = U_pre * w11[:, None]
                        V = V_pre * w11[:, None]
                    else:
                        U = fnp.zeros((n, 0), dtype=fnp.float32)
                        V = fnp.zeros((n, 0), dtype=fnp.float32)
                else:
                    U = fnp.concatenate([U_pre * w11[:, None], A2, eye_n], axis=1)
                    V = fnp.concatenate([V_pre * w11[:, None], 3.0 * eye_n * w21[None, :], A_ds], axis=1)
                    num_new = U.shape[1] - len(col_birth_layers)
                    col_birth_layers.extend([l] * num_new)

                if l in comp_layers and not has_penult:
                    old_idx = [i for i, b_l in enumerate(col_birth_layers) if b_l < l]
                    new_idx = [i for i, b_l in enumerate(col_birth_layers) if b_l == l]
                    if len(old_idx) > 0:
                        cur_ret = per_layer_ret.get(l, 0.8)
                        num_to_keep = max(1, int(len(old_idx) * cur_ret))
                        norm_u_sq = fnp.sum(U[:, old_idx]**2, axis=0)
                        norm_v = fnp.sqrt(fnp.sum(V[:, old_idx]**2, axis=0))
                        scores = norm_u_sq * norm_v
                        sorted_idx = fnp.argsort(scores, kind="stable").tolist()
                        top_local = sorted_idx[-num_to_keep:]
                        kept_old_idx = [old_idx[i] for i in top_local]
                        kept_all = sorted(kept_old_idx + new_idx)
                        U = U[:, kept_all]
                        V = V[:, kept_all]
                        col_birth_layers = [col_birth_layers[i] for i in kept_all]

            # --- State Update ---
            mu = k1
            cov = k11.copy()
            fnp.fill_diagonal(cov, k2)
            cov = _sym(cov)

            # Layer 0 exact conversion for angular
            if l == 0 and is_angular:
                mu = mu / A1_CONST
                cov = cov - (1.0 / (A1_CONST**2) - 1.0) * (k1[:, None] * k1[None, :])
                cov = _sym(cov)

            if use_k4:
                a2_w = w(1, 2)
                b2_w = w(2, 2)
                H_w = 0.5 * (cov11**2) + 0.25 * s22
                rows_E22 = (
                    a2_w * (cov11 @ a2_w)
                    + 0.5 * (a2_w * (s21.T @ b2_w) + b2_w * (s21 @ a2_w))
                    + b2_w * (H_w @ b2_w)
                )
                p_vec = pk1
                D21_mat = pk21
                B11_mat = pk11
                r22_vec = (
                    rows_E22
                    - 2.0 * (D21_mat @ p_vec + p_vec * fnp.sum(D21_mat, axis=0))
                    - 2.0 * fnp.sum(B11_mat**2, axis=1)
                    + 4.0 * p_vec * (B11_mat @ p_vec)
                )
                t22_sum = float(fnp.sum(r22_vec))
                c4 = float((3.0 / (n * (n + 2))) * (fnp.sum(k4) + t22_sum))
            else:
                c4 = 0.0

            preds.append(mu * A1_CONST if is_angular else mu)

        return fnp.stack(preds, axis=0)
