"""Phase 6.5 Candidate: P65-02a-struc
Description: Structured newborn transport
Autogenerated standalone estimator for Phase 6.5.
Pure flopscope.numpy and native flopscope operations only.
"""

from __future__ import annotations

import flopscope as flops
import flopscope.numpy as fnp
from whestbench import BaseEstimator, SetupContext
from whestbench.domain import MLP

try:
    flops.configure(symmetry_warnings=False)
except Exception:
    pass


def _wick_base(mean, var):
    sigma = fnp.sqrt(fnp.maximum(var, fnp.asarray(1e-12, dtype=fnp.float32)))
    alpha = mean / sigma
    return sigma, alpha, flops.stats.norm.pdf(alpha).astype(fnp.float32), flops.stats.norm.cdf(alpha).astype(fnp.float32)


def _relu_wick(mean: fnp.ndarray, var: fnp.ndarray, k: int, p: int, base=None) -> fnp.ndarray:
    """Closed-form Gaussian ReLU Wick expectation E[d^k ReLU(Z)^p] in float32."""
    sigma, alpha, phi, cdf = _wick_base(mean, var) if base is None else base

    if p == 1:
        if k == 0:
            return sigma * phi + mean * cdf
        if k == 1:
            return cdf
        if k == 2:
            return phi / sigma
        if k == 3:
            return -alpha * phi / (sigma**2)
        if k == 4:
            return (alpha**2 - 1.0) * phi / (sigma**3)
    elif p == 2:
        if k == 0:
            return (mean**2 + var) * cdf + mean * sigma * phi
        if k == 1:
            return 2.0 * (sigma * phi + mean * cdf)
        if k == 2:
            return 2.0 * cdf
        if k == 3:
            return 2.0 * phi / sigma
        if k == 4:
            return -2.0 * alpha * phi / (sigma**2)
    elif p == 3:
        if k == 0:
            return (sigma**3) * ((2.0 + alpha**2) * phi + (3.0 * alpha + alpha**3) * cdf)
        if k == 1:
            return 3.0 * (sigma**2) * (alpha * phi + (1.0 + alpha**2) * cdf)
        if k == 2:
            return 6.0 * (sigma * phi + mean * cdf)
        if k == 3:
            return 6.0 * cdf
        if k == 4:
            return 6.0 * phi / sigma
    elif p == 4:
        if k == 0:
            return (sigma**4) * ((5.0 * alpha + alpha**3) * phi + (3.0 + 6.0 * alpha**2 + alpha**4) * cdf)
        if k == 1:
            return 4.0 * (sigma**3) * ((2.0 + alpha**2) * phi + (3.0 * alpha + alpha**3) * cdf)
        if k == 2:
            return 12.0 * (sigma**2) * (alpha * phi + (1.0 + alpha**2) * cdf)
        if k == 3:
            return 24.0 * (sigma * phi + mean * cdf)
        if k == 4:
            return 24.0 * cdf

    raise ValueError(f"Unsupported Wick pair (k={k}, p={p})")


def _zero_diag(mat: fnp.ndarray) -> fnp.ndarray:
    res = mat.copy()
    fnp.fill_diagonal(res, 0.0)
    return res


def _sym(mat: fnp.ndarray) -> fnp.ndarray:
    return 0.5 * (mat + mat.T)


class Estimator(BaseEstimator):
    """Candidate estimator: P65-02a-struc."""

    def setup(self, ctx: SetupContext) -> None:
        _ = ctx
        dummy_mean = fnp.zeros(4, dtype=fnp.float32)
        dummy_var = fnp.ones(4, dtype=fnp.float32)
        _ = _relu_wick(dummy_mean, dummy_var, 0, 1)

    def predict(self, mlp: MLP, budget: int) -> fnp.ndarray:
        _ = budget
        depth = mlp.depth
        n = mlp.width
        eye_n = fnp.eye(n, dtype=fnp.float32)

        mu = fnp.zeros(n, dtype=fnp.float32)
        cov = fnp.eye(n, dtype=fnp.float32)
        U = fnp.zeros((n, 0), dtype=fnp.float32)
        V = fnp.zeros((n, 0), dtype=fnp.float32)
        c4 = 0.0
        q = fnp.zeros(n, dtype=fnp.float32)

        col_birth_layers: list[int] = []
        comp_layers = {10, 13, 6}
        default_retention = 0.62
        per_layer_ret = None
        rank_caps = None

        # Structured newborn descriptors: (A2, h, A_ds) if enabled
        has_newborn = False
        nb_A2 = None
        nb_h = None
        nb_A_ds = None

        preds = []
        terminal_penultimate_H = None
        terminal_g_final = None

        for l in range(depth):
            W_ref = fnp.asarray(mlp.weights[l], dtype=fnp.float32).T

            # --- Terminal layer ---
            if l == depth - 1:
                mu_pre = W_ref @ mu
                var_pre = fnp.sum((W_ref @ cov) * W_ref, axis=1)
                d_M = fnp.sum(W_ref * W_ref, axis=1)

                if has_newborn:
                    U_cur = fnp.concatenate([U, nb_A2, eye_n], axis=1)
                    V_cur = fnp.concatenate([V, 3.0 * eye_n * nb_h[None, :], nb_A_ds], axis=1)
                    U_pre = W_ref @ U_cur
                    V_pre = W_ref @ V_cur
                    s3 = fnp.sum(U_pre * U_pre * V_pre, axis=1)
                elif U.shape[1]:
                    U_pre = W_ref @ U
                    V_pre = W_ref @ V
                    s3 = fnp.sum(U_pre * U_pre * V_pre, axis=1)
                else:
                    s3 = fnp.zeros(n, dtype=fnp.float32)

                s4 = c4 * (d_M**2)

                base = _wick_base(mu_pre, var_pre)
                mu = (_relu_wick(mu_pre, var_pre, 0, 1, base)
                      + _relu_wick(mu_pre, var_pre, 3, 1, base) * s3 / 6.0
                      + _relu_wick(mu_pre, var_pre, 4, 1, base) * s4 / 24.0)
                preds.append(mu)
                break

            # --- 1. Linear step ---

            mu_pre = W_ref @ mu
            cov_pre = _sym(W_ref @ cov @ W_ref.T)
            M = W_ref @ W_ref.T
            d_M = fnp.diag(M)

            if l > 0 and has_newborn:
                # P65-02a: Structured newborn transport
                path_U_pre = W_ref @ nb_A2
                path_V_pre = 3.0 * W_ref * nb_h[None, :]
                slice_U_pre = W_ref
                slice_V_pre = W_ref @ nb_A_ds
                if U.shape[1] > 0:
                    old_U_pre = W_ref @ U
                    old_V_pre = W_ref @ V
                    U_pre = fnp.concatenate([old_U_pre, path_U_pre, slice_U_pre], axis=1)
                    V_pre = fnp.concatenate([old_V_pre, path_V_pre, slice_V_pre], axis=1)
                else:
                    U_pre = fnp.concatenate([path_U_pre, slice_U_pre], axis=1)
                    V_pre = fnp.concatenate([path_V_pre, slice_V_pre], axis=1)
                has_newborn = False
                nb_A2 = None
                nb_h = None
                nb_A_ds = None
                R = U_pre.shape[1]
                s3 = fnp.sum(U_pre * U_pre * V_pre, axis=1)
                sum_pre = 2.0 * ((U_pre * V_pre) @ U_pre.T) + (U_pre * U_pre) @ V_pre.T
                s21 = (1.0 / 3.0) * _zero_diag(sum_pre)
            elif l > 0:
                R = U.shape[1]
                if R > 0:
                    U_pre = W_ref @ U
                    V_pre = W_ref @ V
                    s3 = fnp.sum(U_pre * U_pre * V_pre, axis=1)
                    sum_pre = 2.0 * ((U_pre * V_pre) @ U_pre.T) + (U_pre * U_pre) @ V_pre.T
                    s21 = (1.0 / 3.0) * _zero_diag(sum_pre)
                else:
                    U_pre = fnp.zeros((n, 0), dtype=fnp.float32)
                    V_pre = fnp.zeros((n, 0), dtype=fnp.float32)
                    s3 = fnp.zeros(n, dtype=fnp.float32)
                    s21 = fnp.zeros((n, n), dtype=fnp.float32)
                    sum_pre = fnp.zeros((n, n), dtype=fnp.float32)
            else:
                U_pre = fnp.zeros((n, 0), dtype=fnp.float32)
                V_pre = fnp.zeros((n, 0), dtype=fnp.float32)
                s3 = fnp.zeros(n, dtype=fnp.float32)
                s21 = fnp.zeros((n, n), dtype=fnp.float32)
                sum_pre = fnp.zeros((n, n), dtype=fnp.float32)

            s4 = c4 * (d_M**2)
            s22 = (1.0 / 3.0) * c4 * _zero_diag(d_M[:, None] * d_M[None, :] + 2.0 * (M**2))

            # --- 2. Nonlinear step ---
            var_pre = fnp.diag(cov_pre)
            base = _wick_base(mu_pre, var_pre)
            wick_cache = {}

            def w(k, p):
                key = (k, p)
                if key not in wick_cache:
                    wick_cache[key] = _relu_wick(mu_pre, var_pre, k, p, base)
                return wick_cache[key]

            cov11 = _zero_diag(cov_pre)

            # 3. pK slices
            pk = {}
            for p in (1, 2, 3, 4):
                pk[(p,)] = w(0, p) + (1.0 / 6.0) * w(3, p) * s3 + (1.0 / 24.0) * w(4, p) * s4

            pk[(1, 1)] = _sym(
                cov11 * (w(1, 1)[:, None] * w(1, 1)[None, :])
                + s21.T * (w(1, 1)[:, None] * w(2, 1)[None, :])
                + 0.5 * (cov11**2) * (w(2, 1)[:, None] * w(2, 1)[None, :])
                + 0.25 * s22 * (w(2, 1)[:, None] * w(2, 1)[None, :])
            )

            pk[(2, 1)] = (
                cov11 * (w(1, 2)[:, None] * w(1, 1)[None, :])
                + 0.5 * s21.T * (w(1, 2)[:, None] * w(2, 1)[None, :])
                + 0.5 * s21 * (w(2, 2)[:, None] * w(1, 1)[None, :])
                + 0.5 * (cov11**2) * (w(2, 2)[:, None] * w(2, 1)[None, :])
                + 0.25 * s22 * (w(2, 2)[:, None] * w(2, 1)[None, :])
            )

            pk[(2, 2)] = _sym(
                cov11 * (w(1, 2)[:, None] * w(1, 2)[None, :])
                + s21.T * (w(1, 2)[:, None] * w(2, 2)[None, :])
                + 0.5 * (cov11**2) * (w(2, 2)[:, None] * w(2, 2)[None, :])
                + 0.25 * s22 * (w(2, 2)[:, None] * w(2, 2)[None, :])
            )

            # 4. Invert pK to K
            pk1, pk2, pk3, pk4 = pk[(1,)], pk[(2,)], pk[(3,)], pk[(4,)]
            pk11, pk21 = pk[(1, 1)], pk[(2, 1)]

            k1 = pk1
            k2 = pk2 - pk1**2
            k3 = pk3 - 3.0 * pk1 * pk2 + 2.0 * (pk1**3)
            k4 = pk4 - 4.0 * pk1 * pk3 - 3.0 * (pk2**2) + 12.0 * (pk1**2) * pk2 - 6.0 * (pk1**4)
            k11 = pk11
            k21 = _zero_diag(pk21 - 2.0 * (pk1[:, None] * pk11))

            k22 = _zero_diag(
                pk[(2, 2)]
                - 2.0 * (pk1[None, :] * pk21 + pk1[:, None] * pk21.T)
                - 2.0 * (pk11**2)
                + 4.0 * (pk1[:, None] * pk1[None, :] * pk11)
            )

            w11 = w(1, 1)
            w21 = w(2, 1)

            # 5. Closed-form exact Step 5
            s3_pk = s3 * (w11**3)
            A2 = w11[:, None] * cov11
            C2 = (w21[:, None] * w11[None, :] * cov11).T
            s21_pk = (1.0 / 3.0) * _zero_diag(
                sum_pre * (w11[:, None]**2) * (w11[None, :]) + 3.0 * (A2 * C2)
            )

            k3_ds = k3 - s3_pk
            k21_ds = k21 - s21_pk
            A_ds = fnp.diag(k3_ds) + 3.0 * k21_ds.T

            # Retain structured descriptors for newborn blocks
            has_newborn = True
            nb_A2 = A2
            nb_h = w21
            nb_A_ds = A_ds

            # Existing columns get row gain w11
            if U_pre.shape[1] > 0:
                U = U_pre * w11[:, None]
                V = V_pre * w11[:, None]
            else:
                U = fnp.zeros((n, 0), dtype=fnp.float32)
                V = fnp.zeros((n, 0), dtype=fnp.float32)

            num_new_cols = 2 * n
            col_birth_layers.extend([l] * num_new_cols)

            # 6. Norm pruning at scheduled layers
            if l in comp_layers:
                old_idx = [i for i, b_l in enumerate(col_birth_layers) if b_l < l]
                new_idx = [i for i, b_l in enumerate(col_birth_layers) if b_l == l]

                if len(old_idx) > 0:
                    cur_ret = per_layer_ret.get(l, default_retention) if per_layer_ret else default_retention
                    if rank_caps and l in rank_caps:
                        cap = rank_caps[l]
                        num_to_keep = max(1, min(len(old_idx), cap - 2 * n))
                    else:
                        num_to_keep = max(1, int(len(old_idx) * cur_ret))

                    norm_u_sq = fnp.sum(U[:, old_idx]**2, axis=0)
                    norm_v = fnp.sqrt(fnp.sum(V[:, old_idx]**2, axis=0))
                    scores = norm_u_sq * norm_v
                    sorted_indices = fnp.argsort(scores, kind="stable").tolist()
                    top_local = sorted_indices[-num_to_keep:]
                    kept_old_idx = [old_idx[i] for i in top_local]
                    kept_all = sorted(kept_old_idx + new_idx)

                    U = U[:, kept_all]
                    V = V[:, kept_all]
                    col_birth_layers = [col_birth_layers[i] for i in kept_all]

            # 7. Update state
            mu = k1
            cov = k11.copy()
            fnp.fill_diagonal(cov, k2)
            cov = _sym(cov)

            c4 = float((3.0 / (n * (n + 2))) * (fnp.sum(k4) + fnp.sum(k22)))

            preds.append(mu)

        return fnp.stack(preds, axis=0)
