"""p65_build_candidate.py

Standalone Candidate Generator for Phase 6.5.
Emits complete, self-contained single-file estimators into candidates/estimator_p65_<exp_id>.py.
Strictly zero runtime imports from research helpers or external numpy.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List, Optional

REPO_ROOT = Path(__file__).resolve().parent.parent
WORKSPACE_ROOT = REPO_ROOT.parent
CANDIDATES_DIR = WORKSPACE_ROOT / "candidates"
CONFIGS_DIR = REPO_ROOT / "research" / "phase6_5" / "configs"


def format_exp_filename(exp_id: str) -> str:
    cleaned = exp_id
    if cleaned.startswith("P65-"):
        cleaned = cleaned[4:]
    cleaned = cleaned.replace("-", "_")
    return f"estimator_p65_{cleaned}.py"


def generate_candidate_code(config: Dict[str, Any]) -> str:
    """Generate standalone estimator source code from config dictionary."""
    exp_id = config.get("exp_id", "custom")
    desc = config.get("description", "Phase 6.5 candidate")

    # Options
    use_structured_transport = config.get("structured_transport", False)
    use_scalar_k4 = config.get("scalar_k4_specialization", False)
    use_terminal_split = config.get("terminal_split", False)
    comp_layers = config.get("comp_layers", [6, 10, 13])
    retention = config.get("retention", 0.62)
    per_layer_retention = config.get("per_layer_retention", None)
    rank_caps = config.get("rank_caps", None)  # dict or int
    selector = config.get("selector", "norm_upper")  # 'norm_upper', 'norm_exact', 'birth_pairs', 'diag_response'

    # Compensation & Reweighting
    use_compensation = config.get("slice_compensation", False)
    comp_active_layers = config.get("compensation_layers", [10])

    use_reweighting = config.get("reweighting", False)
    reweight_layers = config.get("reweight_layers", [10])
    reweight_lambda = config.get("reweight_lambda", 1e-3)

    # Q extension (P65-07)
    use_q = config.get("use_q", False)
    q_start = config.get("q_start", 13)
    q_eta = config.get("q_eta", 0.5)

    # CV extension (P65-08)
    use_cv = config.get("use_cv", False)
    cv_N = config.get("cv_N", 512)
    cv_alpha = config.get("cv_alpha", 0.05)

    code = f'''"""Phase 6.5 Candidate: {exp_id}
Description: {desc}
Autogenerated standalone estimator for Phase 6.5.
Pure flopscope.numpy and native flopscope operations only.
"""

from __future__ import annotations

import flopscope as flops
import flopscope.numpy as fnp
from whestbench import BaseEstimator, SetupContext
from whestbench.domain import MLP

try:
    flops.configure(symmetry_warnings=False)
except Exception:
    pass


def _wick_base(mean, var):
    sigma = fnp.sqrt(fnp.maximum(var, fnp.asarray(1e-12, dtype=fnp.float32)))
    alpha = mean / sigma
    return sigma, alpha, flops.stats.norm.pdf(alpha).astype(fnp.float32), flops.stats.norm.cdf(alpha).astype(fnp.float32)


def _relu_wick(mean: fnp.ndarray, var: fnp.ndarray, k: int, p: int, base=None) -> fnp.ndarray:
    """Closed-form Gaussian ReLU Wick expectation E[d^k ReLU(Z)^p] in float32."""
    sigma, alpha, phi, cdf = _wick_base(mean, var) if base is None else base

    if p == 1:
        if k == 0:
            return sigma * phi + mean * cdf
        if k == 1:
            return cdf
        if k == 2:
            return phi / sigma
        if k == 3:
            return -alpha * phi / (sigma**2)
        if k == 4:
            return (alpha**2 - 1.0) * phi / (sigma**3)
    elif p == 2:
        if k == 0:
            return (mean**2 + var) * cdf + mean * sigma * phi
        if k == 1:
            return 2.0 * (sigma * phi + mean * cdf)
        if k == 2:
            return 2.0 * cdf
        if k == 3:
            return 2.0 * phi / sigma
        if k == 4:
            return -2.0 * alpha * phi / (sigma**2)
    elif p == 3:
        if k == 0:
            return (sigma**3) * ((2.0 + alpha**2) * phi + (3.0 * alpha + alpha**3) * cdf)
        if k == 1:
            return 3.0 * (sigma**2) * (alpha * phi + (1.0 + alpha**2) * cdf)
        if k == 2:
            return 6.0 * (sigma * phi + mean * cdf)
        if k == 3:
            return 6.0 * cdf
        if k == 4:
            return 6.0 * phi / sigma
    elif p == 4:
        if k == 0:
            return (sigma**4) * ((5.0 * alpha + alpha**3) * phi + (3.0 + 6.0 * alpha**2 + alpha**4) * cdf)
        if k == 1:
            return 4.0 * (sigma**3) * ((2.0 + alpha**2) * phi + (3.0 * alpha + alpha**3) * cdf)
        if k == 2:
            return 12.0 * (sigma**2) * (alpha * phi + (1.0 + alpha**2) * cdf)
        if k == 3:
            return 24.0 * (sigma * phi + mean * cdf)
        if k == 4:
            return 24.0 * cdf

    raise ValueError(f"Unsupported Wick pair (k={{k}}, p={{p}})")


def _zero_diag(mat: fnp.ndarray) -> fnp.ndarray:
    res = mat.copy()
    fnp.fill_diagonal(res, 0.0)
    return res


def _sym(mat: fnp.ndarray) -> fnp.ndarray:
    return 0.5 * (mat + mat.T)


class Estimator(BaseEstimator):
    """Candidate estimator: {exp_id}."""

    def setup(self, ctx: SetupContext) -> None:
        _ = ctx
        dummy_mean = fnp.zeros(4, dtype=fnp.float32)
        dummy_var = fnp.ones(4, dtype=fnp.float32)
        _ = _relu_wick(dummy_mean, dummy_var, 0, 1)

    def predict(self, mlp: MLP, budget: int) -> fnp.ndarray:
        _ = budget
        depth = mlp.depth
        n = mlp.width
        eye_n = fnp.eye(n, dtype=fnp.float32)

        mu = fnp.zeros(n, dtype=fnp.float32)
        cov = fnp.eye(n, dtype=fnp.float32)
        U = fnp.zeros((n, 0), dtype=fnp.float32)
        V = fnp.zeros((n, 0), dtype=fnp.float32)
        c4 = 0.0
        q = fnp.zeros(n, dtype=fnp.float32)

        col_birth_layers: list[int] = []
        comp_layers = {set(comp_layers)}
        default_retention = {retention}
        per_layer_ret = {per_layer_retention}
        rank_caps = {rank_caps}

        # Structured newborn descriptors: (A2, h, A_ds) if enabled
        has_newborn = False
        nb_A2 = None
        nb_h = None
        has_penult = False
        penult_A2 = None
        penult_h = None
        penult_A_ds = None

        preds = []
        terminal_penultimate_H = None
        terminal_g_final = None

        for l in range(depth):
            W_ref = fnp.asarray(mlp.weights[l], dtype=fnp.float32).T

            # --- Terminal layer ---
            if l == depth - 1:
                mu_pre = W_ref @ mu
                var_pre = fnp.sum((W_ref @ cov) * W_ref, axis=1)
                d_M = fnp.sum(W_ref * W_ref, axis=1)
'''

    if use_terminal_split:
        code += '''
                # P65-02c Split terminal contraction
                if has_penult:
                    d_terminal_old = fnp.sum((W_ref @ U)**2 * (W_ref @ V), axis=1) if U.shape[1] else fnp.zeros(n, dtype=fnp.float32)
                    d_terminal_path = 3.0 * fnp.sum((W_ref @ penult_A2)**2 * W_ref * penult_h[None, :], axis=1)
                    d_terminal_slice = fnp.sum((W_ref**2) * (W_ref @ penult_A_ds), axis=1)
                    s3 = d_terminal_old + d_terminal_path + d_terminal_slice
                elif has_newborn:
                    d_terminal_old = fnp.sum((W_ref @ U)**2 * (W_ref @ V), axis=1) if U.shape[1] else fnp.zeros(n, dtype=fnp.float32)
                    d_terminal_path = 3.0 * fnp.sum((W_ref @ nb_A2)**2 * W_ref * nb_h[None, :], axis=1)
                    d_terminal_slice = fnp.sum((W_ref**2) * (W_ref @ nb_A_ds), axis=1)
                    s3 = d_terminal_old + d_terminal_path + d_terminal_slice
                else:
                    if U.shape[1]:
                        U_pre = W_ref @ U
                        V_pre = W_ref @ V
                        s3 = fnp.sum(U_pre * U_pre * V_pre, axis=1)
                    else:
                        s3 = fnp.zeros(n, dtype=fnp.float32)
'''
    else:
        code += '''
                if has_newborn:
                    U_cur = fnp.concatenate([U, nb_A2, eye_n], axis=1)
                    V_cur = fnp.concatenate([V, 3.0 * eye_n * nb_h[None, :], nb_A_ds], axis=1)
                    U_pre = W_ref @ U_cur
                    V_pre = W_ref @ V_cur
                    s3 = fnp.sum(U_pre * U_pre * V_pre, axis=1)
                elif U.shape[1]:
                    U_pre = W_ref @ U
                    V_pre = W_ref @ V
                    s3 = fnp.sum(U_pre * U_pre * V_pre, axis=1)
                else:
                    s3 = fnp.zeros(n, dtype=fnp.float32)
'''

    if use_q:
        code += f'''
                if l >= {q_start}:
                    b_term = (W_ref**2) @ q
                    s4 = c4 * (d_M**2) + d_M * b_term
                else:
                    s4 = c4 * (d_M**2)
'''
    else:
        code += '''
                s4 = c4 * (d_M**2)
'''

    code += '''
                base = _wick_base(mu_pre, var_pre)
                terminal_g_final = base[3]
                mu = (_relu_wick(mu_pre, var_pre, 0, 1, base)
                      + _relu_wick(mu_pre, var_pre, 3, 1, base) * s3 / 6.0
                      + _relu_wick(mu_pre, var_pre, 4, 1, base) * s4 / 24.0)
                preds.append(mu)
                break

            # --- 1. Linear step ---
'''

    if use_scalar_k4:
        code += '''
            if l == 0:
                M = W_ref @ W_ref.T
                cov_pre = _sym(M)
                mu_pre = fnp.zeros(n, dtype=fnp.float32)
                d_M = fnp.diag(M)
                U_pre = fnp.zeros((n, 0), dtype=fnp.float32)
                V_pre = fnp.zeros((n, 0), dtype=fnp.float32)
                s3 = fnp.zeros(n, dtype=fnp.float32)
                s21 = fnp.zeros((n, n), dtype=fnp.float32)
                sum_pre = fnp.zeros((n, n), dtype=fnp.float32)
            else:
                mu_pre = W_ref @ mu
                cov_pre = _sym(W_ref @ cov @ W_ref.T)
                M = W_ref @ W_ref.T
                d_M = fnp.diag(M)
'''
    else:
        code += '''
            mu_pre = W_ref @ mu
            cov_pre = _sym(W_ref @ cov @ W_ref.T)
            M = W_ref @ W_ref.T
            d_M = fnp.diag(M)
'''

    if use_structured_transport:
        code += '''
            if l > 0 and has_newborn:
                # P65-02a: Structured newborn transport
                path_U_pre = W_ref @ nb_A2
                path_V_pre = 3.0 * W_ref * nb_h[None, :]
                slice_U_pre = W_ref
                slice_V_pre = W_ref @ nb_A_ds
                if U.shape[1] > 0:
                    old_U_pre = W_ref @ U
                    old_V_pre = W_ref @ V
                    U_pre = fnp.concatenate([old_U_pre, path_U_pre, slice_U_pre], axis=1)
                    V_pre = fnp.concatenate([old_V_pre, path_V_pre, slice_V_pre], axis=1)
                else:
                    U_pre = fnp.concatenate([path_U_pre, slice_U_pre], axis=1)
                    V_pre = fnp.concatenate([path_V_pre, slice_V_pre], axis=1)
                has_newborn = False
                nb_A2 = None
                nb_h = None
                nb_A_ds = None
                R = U_pre.shape[1]
                s3 = fnp.sum(U_pre * U_pre * V_pre, axis=1)
                sum_pre = 2.0 * ((U_pre * V_pre) @ U_pre.T) + (U_pre * U_pre) @ V_pre.T
                s21 = (1.0 / 3.0) * _zero_diag(sum_pre)
            elif l > 0:
                R = U.shape[1]
                if R > 0:
                    U_pre = W_ref @ U
                    V_pre = W_ref @ V
                    s3 = fnp.sum(U_pre * U_pre * V_pre, axis=1)
                    sum_pre = 2.0 * ((U_pre * V_pre) @ U_pre.T) + (U_pre * U_pre) @ V_pre.T
                    s21 = (1.0 / 3.0) * _zero_diag(sum_pre)
                else:
                    U_pre = fnp.zeros((n, 0), dtype=fnp.float32)
                    V_pre = fnp.zeros((n, 0), dtype=fnp.float32)
                    s3 = fnp.zeros(n, dtype=fnp.float32)
                    s21 = fnp.zeros((n, n), dtype=fnp.float32)
                    sum_pre = fnp.zeros((n, n), dtype=fnp.float32)
            else:
                U_pre = fnp.zeros((n, 0), dtype=fnp.float32)
                V_pre = fnp.zeros((n, 0), dtype=fnp.float32)
                s3 = fnp.zeros(n, dtype=fnp.float32)
                s21 = fnp.zeros((n, n), dtype=fnp.float32)
                sum_pre = fnp.zeros((n, n), dtype=fnp.float32)
'''
    else:
        code += '''
            if l > 0:
                R = U.shape[1]
                if R > 0:
                    U_pre = W_ref @ U
                    V_pre = W_ref @ V
                    s3 = fnp.sum(U_pre * U_pre * V_pre, axis=1)
                    sum_pre = 2.0 * ((U_pre * V_pre) @ U_pre.T) + (U_pre * U_pre) @ V_pre.T
                    s21 = (1.0 / 3.0) * _zero_diag(sum_pre)
                else:
                    U_pre = fnp.zeros((n, 0), dtype=fnp.float32)
                    V_pre = fnp.zeros((n, 0), dtype=fnp.float32)
                    s3 = fnp.zeros(n, dtype=fnp.float32)
                    s21 = fnp.zeros((n, n), dtype=fnp.float32)
                    sum_pre = fnp.zeros((n, n), dtype=fnp.float32)
            else:
                U_pre = fnp.zeros((n, 0), dtype=fnp.float32)
                V_pre = fnp.zeros((n, 0), dtype=fnp.float32)
                s3 = fnp.zeros(n, dtype=fnp.float32)
                s21 = fnp.zeros((n, n), dtype=fnp.float32)
                sum_pre = fnp.zeros((n, n), dtype=fnp.float32)
'''

    if use_q:
        code += f'''
            if l >= {q_start}:
                Qp = (W_ref * q[None, :]) @ W_ref.T
                b_diag = fnp.diag(Qp)
                s4 = c4 * (d_M**2) + d_M * b_diag
                s22 = _zero_diag(
                    (1.0 / 3.0) * c4 * (d_M[:, None] * d_M[None, :] + 2.0 * (M**2))
                    + (1.0 / 6.0) * (d_M[:, None] * b_diag[None, :] + b_diag[:, None] * d_M[None, :] + 4.0 * M * Qp)
                )
            else:
                s4 = c4 * (d_M**2)
                s22 = (1.0 / 3.0) * c4 * _zero_diag(d_M[:, None] * d_M[None, :] + 2.0 * (M**2))
'''
    else:
        code += '''
            s4 = c4 * (d_M**2)
            s22 = (1.0 / 3.0) * c4 * _zero_diag(d_M[:, None] * d_M[None, :] + 2.0 * (M**2))
'''

    code += '''
            # --- 2. Nonlinear step ---
            var_pre = fnp.diag(cov_pre)
            base = _wick_base(mu_pre, var_pre)
            wick_cache = {}

            def w(k, p):
                key = (k, p)
                if key not in wick_cache:
                    wick_cache[key] = _relu_wick(mu_pre, var_pre, k, p, base)
                return wick_cache[key]

            cov11 = _zero_diag(cov_pre)

            # 3. pK slices
            pk = {}
            for p in (1, 2, 3, 4):
                pk[(p,)] = w(0, p) + (1.0 / 6.0) * w(3, p) * s3 + (1.0 / 24.0) * w(4, p) * s4

            pk[(1, 1)] = _sym(
                cov11 * (w(1, 1)[:, None] * w(1, 1)[None, :])
                + s21.T * (w(1, 1)[:, None] * w(2, 1)[None, :])
                + 0.5 * (cov11**2) * (w(2, 1)[:, None] * w(2, 1)[None, :])
                + 0.25 * s22 * (w(2, 1)[:, None] * w(2, 1)[None, :])
            )

            pk[(2, 1)] = (
                cov11 * (w(1, 2)[:, None] * w(1, 1)[None, :])
                + 0.5 * s21.T * (w(1, 2)[:, None] * w(2, 1)[None, :])
                + 0.5 * s21 * (w(2, 2)[:, None] * w(1, 1)[None, :])
                + 0.5 * (cov11**2) * (w(2, 2)[:, None] * w(2, 1)[None, :])
                + 0.25 * s22 * (w(2, 2)[:, None] * w(2, 1)[None, :])
            )
'''

    if not use_scalar_k4:
        code += '''
            pk[(2, 2)] = _sym(
                cov11 * (w(1, 2)[:, None] * w(1, 2)[None, :])
                + s21.T * (w(1, 2)[:, None] * w(2, 2)[None, :])
                + 0.5 * (cov11**2) * (w(2, 2)[:, None] * w(2, 2)[None, :])
                + 0.25 * s22 * (w(2, 2)[:, None] * w(2, 2)[None, :])
            )
'''

    code += '''
            # 4. Invert pK to K
            pk1, pk2, pk3, pk4 = pk[(1,)], pk[(2,)], pk[(3,)], pk[(4,)]
            pk11, pk21 = pk[(1, 1)], pk[(2, 1)]

            k1 = pk1
            k2 = pk2 - pk1**2
            k3 = pk3 - 3.0 * pk1 * pk2 + 2.0 * (pk1**3)
            k4 = pk4 - 4.0 * pk1 * pk3 - 3.0 * (pk2**2) + 12.0 * (pk1**2) * pk2 - 6.0 * (pk1**4)
            k11 = pk11
            k21 = _zero_diag(pk21 - 2.0 * (pk1[:, None] * pk11))
'''

    if not use_scalar_k4:
        code += '''
            k22 = _zero_diag(
                pk[(2, 2)]
                - 2.0 * (pk1[None, :] * pk21 + pk1[:, None] * pk21.T)
                - 2.0 * (pk11**2)
                + 4.0 * (pk1[:, None] * pk1[None, :] * pk11)
            )
'''

    code += '''
            w11 = w(1, 1)
            w21 = w(2, 1)

            # 5. Closed-form exact Step 5
            s3_pk = s3 * (w11**3)
            A2 = w11[:, None] * cov11
            C2 = (w21[:, None] * w11[None, :] * cov11).T
            s21_pk = (1.0 / 3.0) * _zero_diag(
                sum_pre * (w11[:, None]**2) * (w11[None, :]) + 3.0 * (A2 * C2)
            )

            k3_ds = k3 - s3_pk
            k21_ds = k21 - s21_pk
            A_ds = fnp.diag(k3_ds) + 3.0 * k21_ds.T
'''

    if use_structured_transport:
        code += '''
            # Retain structured descriptors for newborn blocks
            has_newborn = True
            nb_A2 = A2
            nb_h = w21
            nb_A_ds = A_ds

            # Existing columns get row gain w11
            if U_pre.shape[1] > 0:
                U = U_pre * w11[:, None]
                V = V_pre * w11[:, None]
            else:
                U = fnp.zeros((n, 0), dtype=fnp.float32)
                V = fnp.zeros((n, 0), dtype=fnp.float32)

            num_new_cols = 2 * n
            col_birth_layers.extend([l] * num_new_cols)
'''
    elif use_terminal_split:
        code += '''
            if l == depth - 2:
                has_penult = True
                penult_A2 = A2
                penult_h = w21
                penult_A_ds = A_ds
                if U_pre.shape[1] > 0:
                    U = U_pre * w11[:, None]
                    V = V_pre * w11[:, None]
                else:
                    U = fnp.zeros((n, 0), dtype=fnp.float32)
                    V = fnp.zeros((n, 0), dtype=fnp.float32)
            else:
                U = fnp.concatenate([U_pre * w11[:, None], A2, eye_n], axis=1)
                V = fnp.concatenate([V_pre * w11[:, None], 3.0 * eye_n * w21[None, :], A_ds], axis=1)
                num_new_cols = U.shape[1] - len(col_birth_layers)
                col_birth_layers.extend([l] * num_new_cols)
'''
    else:
        code += '''
            U = fnp.concatenate([U_pre * w11[:, None], A2, eye_n], axis=1)
            V = fnp.concatenate([V_pre * w11[:, None], 3.0 * eye_n * w21[None, :], A_ds], axis=1)
            num_new_cols = U.shape[1] - len(col_birth_layers)
            col_birth_layers.extend([l] * num_new_cols)
'''

    # --- 6. Pruning ---
    code += '''
            # 6. Norm pruning at scheduled layers
            if l in comp_layers:
                old_idx = [i for i, b_l in enumerate(col_birth_layers) if b_l < l]
                new_idx = [i for i, b_l in enumerate(col_birth_layers) if b_l == l]

                if len(old_idx) > 0:
                    cur_ret = per_layer_ret.get(l, default_retention) if per_layer_ret else default_retention
                    if rank_caps and l in rank_caps:
                        cap = rank_caps[l]
                        num_to_keep = max(1, min(len(old_idx), cap - 2 * n))
                    else:
                        num_to_keep = max(1, int(len(old_idx) * cur_ret))
'''

    if selector == "norm_exact":
        code += '''
                    # P65-04a Exact individual-atom norm squared
                    u_sub = U[:, old_idx]
                    v_sub = V[:, old_idx]
                    a_dot = fnp.sum(u_sub * u_sub, axis=0)
                    b_dot = fnp.sum(v_sub * v_sub, axis=0)
                    c_dot = fnp.sum(u_sub * v_sub, axis=0)
                    scores = (a_dot * a_dot * b_dot + 2.0 * a_dot * (c_dot**2)) / 3.0
                    sorted_indices = fnp.argsort(scores, kind="stable").tolist()
'''
    else:
        code += '''
                    norm_u_sq = fnp.sum(U[:, old_idx]**2, axis=0)
                    norm_v = fnp.sqrt(fnp.sum(V[:, old_idx]**2, axis=0))
                    scores = norm_u_sq * norm_v
                    sorted_indices = fnp.argsort(scores, kind="stable").tolist()
'''

    if use_compensation:
        code += f'''
                    # P65-05 Slice compensation
                    if l in {set(comp_active_layers)} and num_to_keep > n:
                        num_to_keep_comp = num_to_keep - n
                        top_local = sorted_indices[-num_to_keep_comp:]
                        kept_old_idx = [old_idx[i] for i in top_local]
                        kept_all = sorted(kept_old_idx + new_idx)
                        U_keep = U[:, kept_all]
                        V_keep = V[:, kept_all]

                        # Compute missing slices
                        d_keep = fnp.sum(U_keep * U_keep * V_keep, axis=1)
                        S_keep = (1.0 / 3.0) * _zero_diag(2.0 * ((U_keep * V_keep) @ U_keep.T) + (U_keep * U_keep) @ V_keep.T)
                        d_missing = k3 - d_keep
                        S_missing = _zero_diag(k21 - S_keep)

                        U_c = eye_n
                        V_c = fnp.diag(d_missing) + 3.0 * S_missing.T
                        U = fnp.concatenate([U_keep, U_c], axis=1)
                        V = fnp.concatenate([V_keep, V_c], axis=1)
                        col_birth_layers = [col_birth_layers[i] for i in kept_all] + [l] * n
                    else:
                        top_local = sorted_indices[-num_to_keep:]
                        kept_old_idx = [old_idx[i] for i in top_local]
                        kept_all = sorted(kept_old_idx + new_idx)
                        U = U[:, kept_all]
                        V = V[:, kept_all]
                        col_birth_layers = [col_birth_layers[i] for i in kept_all]
'''
    else:
        code += '''
                    top_local = sorted_indices[-num_to_keep:]
                    kept_old_idx = [old_idx[i] for i in top_local]
                    kept_all = sorted(kept_old_idx + new_idx)
                    U = U[:, kept_all]
                    V = V[:, kept_all]
                    col_birth_layers = [col_birth_layers[i] for i in kept_all]
'''

    # --- 7. State Update ---
    code += '''
            # 7. Update state
            mu = k1
            cov = k11.copy()
            fnp.fill_diagonal(cov, k2)
            cov = _sym(cov)
'''

    if use_scalar_k4:
        code += '''
            # Section 7 exact k22 sum without allocating full (n, n) E22/k22
            a2_w = w(1, 2)
            b2_w = w(2, 2)
            H_w = 0.5 * (cov11**2) + 0.25 * s22
            rows_E22 = (
                a2_w * (cov11 @ a2_w)
                + 0.5 * (a2_w * (s21.T @ b2_w) + b2_w * (s21 @ a2_w))
                + b2_w * (H_w @ b2_w)
            )
            p_vec = pk1
            D21_mat = pk21
            B11_mat = pk11
            r22_vec = (
                rows_E22
                - 2.0 * (D21_mat @ p_vec + p_vec * fnp.sum(D21_mat, axis=0))
                - 2.0 * fnp.sum(B11_mat**2, axis=1)
                + 4.0 * p_vec * (B11_mat @ p_vec)
            )
            t22_sum = float(fnp.sum(r22_vec))
            c4 = float((3.0 / (n * (n + 2))) * (fnp.sum(k4) + t22_sum))
'''
    else:
        code += '''
            c4 = float((3.0 / (n * (n + 2))) * (fnp.sum(k4) + fnp.sum(k22)))
'''

    if use_q:
        code += f'''
            if l >= {q_start}:
                # Section 13: Traceless diagonal fourth-order state
                Rdiag = k4 + r22_vec if '{use_scalar_k4}' == 'True' else k4 + fnp.sum(k22, axis=1)
                tau = fnp.sum(Rdiag)
                c4 = float(3.0 * tau / (n * (n + 2)))
                q_full = (6.0 / (n + 4)) * (Rdiag - tau / n)
                q = {q_eta} * (q_full - fnp.mean(q_full))
'''

    code += '''
            preds.append(mu)
'''

    if use_cv:
        code += f'''
        # Section 14: Small online K3-centered control variate
        if depth >= 2 and {cv_alpha} > 0:
            rng = fnp.random.default_rng(mlp.seed)
            X_half_max = rng.standard_normal((512, n), dtype=fnp.float32)
            half_N = {cv_N} // 2
            X_half = X_half_max[:half_N]
            X = fnp.concatenate([X_half, -X_half], axis=0)

            H = X
            for l_idx in range(depth - 1):
                A_l = fnp.asarray(mlp.weights[l_idx], dtype=fnp.float32)
                H = fnp.maximum(H @ A_l, 0.0)

            mean_H14 = fnp.mean(H, axis=0)
            A_term = fnp.asarray(mlp.weights[depth - 1], dtype=fnp.float32)
            Y = fnp.maximum(H @ A_term, 0.0)
            mean_Y = fnp.mean(Y, axis=0)

            mu_H = preds[depth - 2]
            mu_Y = preds[-1]
            correction = ((mean_H14 - mu_H) @ A_term) * terminal_g_final
            V = mean_Y - correction
            preds[-1] = (1.0 - {cv_alpha}) * mu_Y + {cv_alpha} * V
'''

    code += '''
        return fnp.stack(preds, axis=0)
'''

    return code


def build_candidate(config: Dict[str, Any]) -> Path:
    exp_id = config["exp_id"]
    filename = format_exp_filename(exp_id)
    out_path = CANDIDATES_DIR / filename
    CANDIDATES_DIR.mkdir(parents=True, exist_ok=True)
    CONFIGS_DIR.mkdir(parents=True, exist_ok=True)

    code = generate_candidate_code(config)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(code)

    config_path = CONFIGS_DIR / f"{exp_id}.json"
    with open(config_path, "w", encoding="utf-8") as f:
        json.dump(config, f, indent=2)

    print(f"[p65_build_candidate] Wrote candidate to: {out_path}")
    print(f"[p65_build_candidate] Wrote config to:    {config_path}")
    return out_path


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", type=str, required=True, help="Path to config JSON or JSON string")
    args = parser.parse_args()

    cfg_p = Path(args.config)
    if cfg_p.exists():
        with open(cfg_p, "r", encoding="utf-8") as f:
            cfg = json.load(f)
    else:
        cfg = json.loads(args.config)

    build_candidate(cfg)
